# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanna_buy_save_first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
