# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanna_buy_save_first', '0002_auto_20160513_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
